### ISSUE TITLE
Post June Newsletter

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#28]
Craig,
Please post, no later than (NLT) 1 June 2019, 
[JCRC Flight Line June 2019 v1.0.pdf](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/3237750/JCRC.Flight.Line.June.2019.v1.0.pdf)
 the attached newsletter to the website tied to both the Latest newsletter link in the News and upcoming events pane on the home page and on the Newsletter Page.

Thanks

**Comment by cquillen** [comment]
Done

@GlennRoss
