### ISSUE TITLE
Post dates and materials for Natl  Model Avn Day

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#29]
Craig,

Anthony asks that the Schedule and event descriptions/rules be posted for National Model Avn  Day by posted to the Web Site.  I've included both the word and .pdf version, your choice .
[National Model Aviation Day Event and Competitions Rules.pdf](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/3330490/National.Model.Aviation.Day.Event.and.Competitions.Rules.pdf)
[National Model Aviation Day Event and Competitions Rules.docx](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/3330501/National.Model.Aviation.Day.Event.and.Competitions.Rules.docx)

**Comment by cquillen** [comment]
Done
