### ISSUE TITLE
Right Field Camera is stuck

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#32]
Right side field camera is stuck at June 30, 2:19 AM

**Comment by cquillen** [comment]
The GFI outlet this camera is plugged into has failed and needs to be
replaced.  The weather resistant outlet box could stand to be replaced as
well.

**Comment by GlennRoss** [comment]
Club Vice President notified 9 July of need to replace GFI outlet and to place waterproof tape around junction of Plate cover with Box to eliminate water dripping into the Box.

**Comment by cquillen** [comment]
I spoke to Tim about this at the last grill&chill.  He said that he had purchased the new outlets.  (There was another one in the gazebo that needs to be replaced as well.)

**Comment by GlennRoss** [comment]
Yeah, I did too, thats what I put in the ticket as a comment.  Thanks
*Glenn C. Ross, II*
134 Chock Creek Road
Johnson City, TN  37601
*423-282-1197*

**Comment by GlennRoss** [comment]
All cameras back on line as of 7 August, validated at 14:45
