### ISSUE TITLE
Post  August Flight Line to web site

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#35]
Please post the attached August Flight Line to the web site and link to both "latest Newsletter" hyper link and on the Newsletter page by 1 Aug.
[JCRC Flight Line August 2019 v1.0.pdf](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/3453338/JCRC.Flight.Line.August.2019.v1.0.pdf)

**Comment by cquillen** [comment]
Done.
