### ISSUE TITLE
Post JCRC By Laws, version 1.0 to Web Site

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#36]
Please take down the Draft By Laws Review document and the associated link from the left Pane of the Home Page.
Post the attached .pdf copy of the new By Laws to the link currently existing  under 'Information" on the right side scroll pane.  Temporarily also  create a link underneath the By-Laws  for the Roberts Rules .pdf, also attached.
[Johnson City Radio Controllers By-Laws version 1_020190819_0042.pdf](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/3517105/Johnson.City.Radio.Controllers.By-Laws.version.1_020190819_0042.pdf)
[JCRC Supplement Document for Roberts Rules of Order.pdf](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/3517114/JCRC.Supplement.Document.for.Roberts.Rules.of.Order.pdf)

Thanks

**Comment by cquillen** [comment]
done
