### ISSUE TITLE
Post 2019 Field Rules and noise document

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#38]
Please post the field rules on the "Field" page off the "Home" Page.  The noise document can go on the JCRC Documents page you've been discussing building where Club centric documents should be maintained.

[JCRC CLUB RULES 2019 v1.0.pdf](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/3556569/JCRC.CLUB.RULES.2019.v1.0.pdf)
[JCRC Standard Method of Sound Measurement Document.pdf](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/3556620/JCRC.Standard.Method.of.Sound.Measurement.Document.pdf)

**Comment by cquillen** [comment]
done
