### ISSUE TITLE
Post new By-Laws .pdf

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#39]
Craig,
Please post this .pdf copy of the By-Laws instead of the .pdf attached with the roberts rules in the earlier git hub request.
[JCRC_BY-LAWS_15_August_2019_v1.0.pdf](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/3643597/JCRC_BY-LAWS_15_August_2019_v1.0.pdf)

**Comment by cquillen** [comment]
done
