### ISSUE TITLE
Replace  field rules version 1.0 with version 1.1 attached and post to web site.

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#40]
Replace  field rules version 1.0 with version 1.1 attached and post to web site.  Version 1.1 is attached
[JCRC CLUB RULES 2019 v1.1.pdf](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/3651429/JCRC.CLUB.RULES.2019.v1.1.pdf)

**Comment by cquillen** [comment]
done
