### ISSUE TITLE
Post dates to calendar

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#41]
Please post the following events and dates to the **_Calendar_** page and to the scrolling _news and upcoming events_ pane on the **_home_** page prior to the 15th of October:

Fall Work Day -  10AM - 3PM, 19 October 2019
Officer Elections and Budget Vote - 6:45 PM, 26 November 2019
First Flight - 11AM - 3 PM, 1 Jan 2020
Indoor Fun Fly - In at Kingsport Civic Auditorium - 1 PM - 5 PM, 1 Feb 2020
Indoor Fun Fly - In at Kingsport Civic Auditorium - 1 PM - 5 PM, 14 March 2020
Spring Fun Fly In, at the Field - 10 AM -3 PM, 25 April 2020
National Model Aviation Day Fly In at the Field - 10 AM - 3 PM, 22 August 2020

**Comment by cquillen** [comment]
done
