### ISSUE TITLE
October Flight Line

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#42]
Please post attached Flight Line for October to the Web Site
[JCRC Flight Line October 2019 v1.0.pdf](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/3667498/JCRC.Flight.Line.October.2019.v1.0.pdf)
 No Later Than 1 October.
Thanks

**Comment by cquillen** [comment]
done
