### ISSUE TITLE
Post August minutes

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#45]
Please post the August Minutes and Addendum (approved at the Sept meeting) which are attached:
[Minutes2019-08-27.docx](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/3775999/Minutes2019-08-27.docx)
[Minutes2019-08-27 Addendum.docx](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/3776000/Minutes2019-08-27.Addendum.docx)

**Comment by cquillen** [comment]
done
