### ISSUE TITLE
Please post 2020 Budget documents for member review

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#47]
Please post the attached for members to review before the Nov Monthly meeting and place a notice in the information page under the "Fly at our Field" requirements with a link to the document.

I've included both the Power Point and the .pdf version; post which ever is easiest and quickest.

[for post to website prior to Nov.pptx](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/3789537/for.post.to.website.prior.to.Nov.pptx)
[for post to website prior to Nov.pdf](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/3789539/for.post.to.website.prior.to.Nov.pdf)

**Comment by cquillen** [comment]
@GlennRoss Done
