### ISSUE TITLE
Update Contact Us Page to reflect 2020 Officers and Board Members

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#50]
Please update the Contact Us page by 1 Jan 2020 with the following:
**President**
Dan Jackson
(423) 723-3522
**Vice President**
Phil Swihart
(321) 514-3247
**Treasurer**
Anthony Hall
(423) 915-9468
**Secretary**
Doug Lindauer
(423) 957-0144
**Safety Officer**
Jerry Black
(423) 418-0887
**Field Marshals:**
Mike Harrison (423) 283-4825
Tim Cox (423) 782-0253
Skip Weller (423) 753-5352
Craig Quillen (423) 384-4621
David Jones (423) 538-4894
Dan Jackson (423) 723-3522
**Newsletter Editor**
Glenn Ross
(423) 282-1197
**Webmaster**
Craig Quillen
(423) 384-4621
**Event Coordinator**
Tim Edwards
(423) 530-4118
**Board Members**
			Term
Jerry Black –2020 – 2025
Craig Quillen –2019 – 2020
Terry Bailey –2019 – 2021
Anthony Hall –2017 – 2022
Vic Koenig –2020 – 2023
Skip Weller -2019 – 2024

**Comment by cquillen** [comment]
@GlennRoss I believe this has been addressed.

**Comment by GlennRoss** [comment]
Yes it has!
*Glenn C. Ross, II*
134 Chock Creek Road
Johnson City, TN  37601
*423-282-1197*
