### ISSUE TITLE
Post Jan 2020 Flight Line Newsletter

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#51]
Please post the attached Jan 2020 Flight Line Newsletter by 1 Jan 2020.
[JCRC Flight Line jan 2020 v1.0.pdf](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/4011078/JCRC.Flight.Line.jan.2020.v1.0.pdf)

**Comment by cquillen** [comment]
@GlennRoss done.
