### ISSUE TITLE
Feb Flight Line

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#53]
Please post the attached Feb 2020 Flight Line Newsletter
[JCRC Flight Line Feb 2020 v1.0.pdf](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/4140626/JCRC.Flight.Line.Feb.2020.v1.0.pdf)

**Comment by cquillen** [comment]
@GlennRoss done
