### ISSUE TITLE
Update Home Page Alert Window Information

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#59]
Please delete the entries about cancelled activities, update the sentence about Chill and Grill to state" Chill and Grill Starts up 2 June at ^ PM and resumes its Tuesday Evening schedule through the End of August".

In the "News and Upcoming Events" Pane, add the start of Chill and Grill on 2 June, Work Day on 13 June starting at 9 AM
Field Spruce up Day on 11 July starting at 9 AM
Senior Pattern Association Two Day Competition on 18 and 19 July, starting 9 AM each Day

**Comment by cquillen** [comment]
done
