### ISSUE TITLE
Post Draft Meeting Minutes, Aug 2020

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#62]
Please post the draft minutes to the website, tied to the "latest minutes" hyperlink. 
[Aug 25 2020 JCRC Meeting Minutes, v1.pdf](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/5132513/Aug.25.2020.JCRC.Meeting.Minutes.v1.pdf)

**Comment by cquillen** [comment]
done
