### ISSUE TITLE
Post 2021 proposed budget to website

### ISSUE THREAD

**Issue by GlennRoss** [JohnsonCityRadioControllers/LegacyWebsite#63]
Please post the FY 2021 Budget Proposal where it should go with a notice in the Info Pane on the left side of the Homepage.
Needs to be done ASAP so that members have 30 days to review before Sept Meeting and vote.
[PROPOSED BUDGET FOR 2021.pdf](https://github.com/JohnsonCityRadioControllers/LegacyWebsite/files/5132520/PROPOSED.BUDGET.FOR.2021.pdf)

**Comment by cquillen** [comment]
done
